plugins {
    id 'base'
    id 'io.github.goooler.shadow' version '8.1.8' apply false
}

subprojects {
    group = 'me.sepehrhn'
    version = findProperty('mod_version') ?: '0.4.0'

    repositories {
        mavenCentral()
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://repo.papermc.io/repository/maven-public/" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }

    pluginManager.withPlugin('java') {
        dependencies {
            testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
            testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }

        tasks.withType(JavaCompile).configureEach {
            options.release.set(25)
            options.encoding = 'UTF-8'
        }
    }
}

tasks.register('copyArtifacts', Copy) {
    dependsOn ':paper:build', ':fabric:build'
    
    doFirst {
        delete layout.buildDirectory.dir('libs')
    }

    from project(':paper').layout.buildDirectory.dir('libs')
    from project(':fabric').layout.buildDirectory.dir('libs')
    include "*-Paper.jar"
    include "*-Fabric.jar"
    into layout.buildDirectory.dir('libs')
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

build.finalizedBy(copyArtifacts)

