plugins {
    id "java"
    id "io.github.goooler.shadow"
}

dependencies {
    implementation project(":core")
    compileOnly "io.papermc.paper:paper-api:${project.paper_api_version}"
    shadow project(":core")
}

base {
    archivesName = "PocketDice-${project.version}-Paper"
}

tasks.withType(Jar).configureEach {
    archiveVersion.set("")
}

assemble.dependsOn shadowJar

shadowJar {
    archiveClassifier.set("") 
}
